### ISSUE TITLE
Missing VCOMP110.DLL on Windows 10

### ISSUE THREAD

**Issue by Chaz6** [syndicodefront/infekt#107]
After upgrading to Windows 10 the application no longer runs. The message displayed is below.

---------------------------
infekt-win64.exe - System Error
---------------------------
The program can't start because VCOMP110.DLL is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------

I have tried re-installing Microsoft Visual C++ 2010 SP1 Redistributable Package (x64) but this did not resolve the problem. I notice that I have VCOMP100.DLL and VCOMP120.DLL but not VCOMP110.DLL in system32.

**Comment by flakes** [comment]
Please read the FAQ: https://infekt.ws/faq.html again, you need the MS VC++ 2012 runtime, not 2010.

**Comment by Chaz6** [comment]
Thanks for the pointer. The installer did not install the correct version.
