### ISSUE TITLE
Touch scrolling doesn't work (Windows 10)

### ISSUE THREAD

**Issue by varoot** [syndicodefront/infekt#108]
I have a Surface Pro. When I use trackpad to scroll, the scrollbar moves but the content doesn't. The same also happens with touchscreen scrolling. Mousewheel works fine btw.

**Comment by flakes** [comment]
Thanks for the report!

* Is this a Surface Pro 2, 3 or 4?
* Do you have all the latest updates for Windows 10 installed?
* Do you experience the issue in any other applications?

**Comment by varoot** [comment]
This is Surface Pro 4. I have all the updates for Windows 10 installed. I don't have this issue with any other applications. This only happens when I tried to drag the main window area in order to scroll. If I drag the scrollbar, it works fine.

**Comment by flakes** [comment]
Thanks, one more question:

If you hold down the CTRL key while using the trackpad in the main window, does the zoom level change or not?

**Comment by varoot** [comment]
You mean holding down CTRL and scroll on trackpad? No, that doesn't zoom it, but I can pinch on the trackpad and on the touchscreen to zoom. That one works.

**Comment by flakes** [comment]
Can you please try this (portable) version and check if it's any better? :8ball: 

https://syndicode.org/infekt/downloads/iNFekt-v0.9.5-SuperCompact_VS14Manifest.rar

**Comment by varoot** [comment]
Hmm... there's no difference at all. I think it's something to do with the renderer realizing it should re-render, because the scrollbar responds correctly to my touch scroll (even in previous version).

For example, when I scroll to the end of content, I see that the scrollbar has reached the bottom, even though the content doesn't move at all (i.e. still at the top). However, if I resize the window then, then it's rendered at the correct position. I hope that makes sense. The behavior is the same for all 3 rendering modes.

**Comment by varoot** [comment]
One more strange behavior due to this bug: If I scroll down using touchpad, then use a keyboard arrow to scroll half the window more. The whole screen moves with the keyboard, but the top half was from the one part of the document (incorrect) and the bottom is from another (correct) part. Let me know if you need me to take a screenshot for this.

**Comment by flakes** [comment]
Thanks for the info, that was helpful! I made an additional change in this version for redrawing the window, maybe it will help: https://syndicode.org/infekt/downloads/iNFekt-v0.9.5-SuperCompact_2016-01-29.rar

**Comment by varoot** [comment]
No, this doesn't solve it.

I also noticed some thing. When I use touchpad or touchscreen to scroll, it triggers "momentum scrolling" where the scrollbar might still keep moving after I lift up my fingers. Maybe this is triggered by different events from normal scrolling?

**Comment by flakes** [comment]
I think I may have found the issue, I did not handle one specific scroll message (_SB_THUMBPOSITION_) - which seems to be generated according to https://msdn.microsoft.com/en-us/library/windows/desktop/dd940543(v=vs.85).aspx. Please try this version: https://syndicode.org/infekt/downloads/iNFekt-v0.9.5-SuperCompact_2016-01-30.rar
If this doesn't help either, I will have to look into fully supporting the gestures (which is not hard, but I can't test it...)

**Comment by varoot** [comment]
Sadly it still doesn't work.

I don't know why the pan/flick gesture doesn't work but the zoom gesture works though.

**Comment by flakes** [comment]
v0.9.6 has just been released, can you please test this one again?

**Comment by varoot** [comment]
No, still doesn't work

**Comment by flakes** [comment]
Won't be fixed in 1.x any more, but 2.0 should have this covered. See issue #151
