### ISSUE TITLE
Internal bug with ansi file

### ISSUE THREAD

**Issue by apometron** [syndicodefront/infekt#112]
Hi! =)

I send to you folks the ansi file which caused the internal problem.

[]s
Rodrigo Cesar Banhara
http://about.me/apometron

[[FI]_BBS.003_Twinkle BBS.ans.zip](https://github.com/syndicodefront/infekt/files/418610/FI._BBS.003_Twinkle.BBS.ans.zip)

**Comment by flakes** [comment]
Thanks for the report, this will be fixed in the next release :-)
