### ISSUE TITLE
Default Program issues

### ISSUE THREAD

**Issue by STaRDoGG** [syndicodefront/infekt#114]
Seems when setting it as the Default Program to open .nfo files:

1). The infekt icon doesn't show for .nfo files; it shows the Windows "Default Program Icon" instead, even when double-clicking the file will still open in in Infekt.

2). Setting the Default program to something else using windows control panel (Default Programs applet), then running Infekt with the "Always check if default" option selected, it doesn't catch that it's not the default viewer. Clicking the Check Now button says it appears to be the default viewer.

**Comment by flakes** [comment]
Please tell your Windows version ;) Have you tried rebooting?

**Comment by STaRDoGG** [comment]
Ahh, sorry. ;)

Windows 10, 64 Bit. Ohh yea. I've rebooted a million times and the problem persists.

**Comment by flakes** [comment]
Thanks again for the report, the next version will include fixes for this :)

**Comment by flakes** [comment]
For future reference:

- https://hg.mozilla.org/mozilla-central/annotate/57a8cde3f08ca9d60bcd8bdd698ceec687f0aed2/browser/components/shell/nsWindowsShellService.cpp#l
- https://bugzilla.mozilla.org/show_bug.cgi?id=1302023
- http://stackoverflow.com/questions/32178986/windows-10-equivalent-of-launchadvancedassociationui
- http://stackoverflow.com/questions/37088950/how-to-focus-the-specific-file-type-in-windows-settings-file-association-page
- https://msdn.microsoft.com/en-us/library/windows/desktop/hh706903(v=vs.85).aspx
- http://stackoverflow.com/questions/32178986/windows-10-equivalent-of-launchadvancedassociationui#answer-38805204
- https://stash.kopano.io/projects/KD/repos/kopano-deskapp/raw/windows/Deskapp%20VS/Deskapp%20Helper/Deskapp%20Helper.cpp?at=d7dba592e1a65b6048166f6be55b07b300fd590c
- https://chromium.googlesource.com/chromium/src/+/master/chrome/installer/util/shell_util.cc
