### ISSUE TITLE
NFO not displayed correctly

### ISSUE THREAD

**Issue by Keith94** [syndicodefront/infekt#116]
The art portion in this NFO looks wrong when displayed with iNFekt: https://www.srrdb.com/download/file/(12_thumpers)-play_the_game_vinyl_housemaster-bmi/%2812_thumpers%29-play_the_game_vinyl_housemaster-bmi.nfo

Here's a comparison with "RetroTxt":

![firefox_2016-12-05_12-52-08](https://cloud.githubusercontent.com/assets/5490615/20901978/e3a3b716-bae9-11e6-8744-5f2fbc53f31c.png)

**Comment by flakes** [comment]
Note: RetroTxt uses 8 spaces for a single tab character.

**Comment by flakes** [comment]
This will be fixed in the next release!
