### ISSUE TITLE
NUL byte prevents NFO from being displayed

### ISSUE THREAD

**Issue by rescene** [syndicodefront/infekt#120]
Example NFO file that fails to be displayed:
https://www.srrdb.com/release/details/Duke_Nukem_Manhattan_Project-FLT

At the end of the game information section is a NUL byte. This prevents the NFO from being properly displayed.

![image](https://cloud.githubusercontent.com/assets/1263861/22595362/8366a936-ea27-11e6-8a5f-df533029b59d.png)

iNFekt shows "Unrecognized file format or broken file."

Can you attempt to display it anyway?
You may still show an error, but I prefer a non interactive message. (like browser warnings at the top of a web page)

**Comment by flakes** [comment]
Works fine in 0.9.7. Please recheck ;)

**Comment by rescene** [comment]
It works fine indeed!
Very weird. Nothing changed. I guess I reported it from another system.
