### ISSUE TITLE
Line wrapping behavior and art

### ISSUE THREAD

**Issue by pyrescene** [syndicodefront/infekt#121]
I'm not completely satisfied by the line wrapping behavior yet. See https://github.com/syndicodefront/infekt/issues/105 and https://github.com/syndicodefront/infekt/issues/91

What I want from this feature is to wrap a really long line of text so I can easily read it. This works as expected.

![image](https://cloud.githubusercontent.com/assets/1263861/22596295/3df6e27c-ea2b-11e6-8d91-bc6b2d6a8824.png)

Then there are some newer groups that have a really wide nfo. With wrap on it still shows nicely on my screen. (155 chars in example)

![image](https://cloud.githubusercontent.com/assets/1263861/22596399/b511a306-ea2b-11e6-87c1-9fd5aa461984.png)

While the above all get displayed as expected, this smaller art doesn't. (141 characters including white space) Example files on https://www.srrdb.com/browse/group:sparood/1

![image](https://cloud.githubusercontent.com/assets/1263861/22596519/2b562870-ea2c-11e6-9845-482e12cc8306.png)

This generated text, which could happen in a scene notice, doesn't wrap.

[lorem.nfo.txt](https://github.com/syndicodefront/infekt/files/751045/lorem.nfo.txt)

Can the wrap magic be improved?

This is where it happens: https://github.com/syndicodefront/infekt/blob/ea93ae9cb28e9d7f8279562702dec234c536553d/src/lib/nfo_data.cpp#L453

Try using this heuristic instead:
One of the lines that got wrapped, must be longer than 2*80 chars, ignoring trailing white space.

**Comment by flakes** [comment]
New algorithm (see commit) will be in next release.
