### ISSUE TITLE
Glow Effect broken below glow radius 8 in v0.9.6 and v0.9.7

### ISSUE THREAD

**Issue by Eselter** [syndicodefront/infekt#122]
When we set glow radius below 8 in version 0.9.6 or 0.9.7 glow effect have some problem with text placement. On v0.9.5 all working fine with glow radius 1-7.

Some screens:

in v0.9.5 (glow radius 7)
![image](https://cloud.githubusercontent.com/assets/8573382/25976214/c3c93d26-36b3-11e7-9ff4-3cf107b92711.png)

in v0.9.7 (glow radius 7)
![image](https://cloud.githubusercontent.com/assets/8573382/25976245/e8f821fc-36b3-11e7-8be6-3113d9a0afb0.png)

**Comment by flakes** [comment]
I'm having a hard time reproducing this, can you please provide?
- export of your rendering settings (Settings -> Export)
- screenshot of your About window (F1)

**Comment by Eselter** [comment]
![about](https://user-images.githubusercontent.com/8573382/30184666-15517eb0-941f-11e7-8c4a-a5b6957a569b.png)

remove .txt
[eselter-nfo-settings.ini.txt](https://github.com/syndicodefront/infekt/files/1286088/eselter-nfo-settings.ini.txt)

**Comment by Keith94** [comment]
I can reproduce the bug. For example [this nfo](https://z0x.us/v32301)'s text turns from black to white (with glow radius <8).

**Comment by flakes** [comment]
Thanks for the input! Does the bug go away if you resize the window horizontally?

**Comment by Keith94** [comment]
For my case with the darksiders nfo:

1. No
2. Yes

**Comment by Eselter** [comment]
1. No
2. Yes

**Comment by flakes** [comment]
Does the Classic mode (F3) work as expected?

**Comment by flakes** [comment]
Can you guys please try one of the following portable builds? I believe that updating libcairo may have fixed the issue:
- https://syndicode.org/infekt/temp/iNFekt-v0.9.8-test-32bit-Portable.rar
- https://syndicode.org/infekt/temp/iNFekt-v0.9.8-test-64bit-Portable.rar

**Comment by Eselter** [comment]
1. Does the Classic mode (F3) work as expected? **Yes**
2. Does the "Use on-demand rendering" setting change/fix anything? **No**

iNFekt-v0.9.8-test-64/32bit-Portable with glow radius 7 (gpu acceleration doesn't matter):
![image](https://user-images.githubusercontent.com/8573382/31141421-a8df4e7a-a877-11e7-9271-da2b7c165823.png)

**Comment by flakes** [comment]
It looks like it could be a compiler optimization bug. Still investigating...

**Comment by flakes** [comment]
New attempt - let me know how it goes!

* https://syndicode.org/infekt/temp/iNFekt-v0.9.8-t2-32bit-Portable.rar
* https://syndicode.org/infekt/temp/iNFekt-v0.9.8-t2-64bit-Portable.rar

**Comment by Eselter** [comment]
Yeah now is 👍
Thanks for fix :)
