### ISSUE TITLE
Default viewer check.

### ISSUE THREAD

**Issue by Achaean** [syndicodefront/infekt#128]
Portable x64 version, always alarms, because it ins't the default viewer (although it is actually).
V.1.0.1 on Win 10 Pro x64 (v.10.0.16299.125).

Maybe an option should be added, for disabling the (buggy) default viewer check?

Installable version doesn't have this problem.

**Comment by flakes** [comment]
Hi,

I can't reproduce this, and the default app handling on Windows 10 has been taken out of application's hands, so please just tick off the "Always check if iNFekt is the default NFO viewer on startup" option from the preferences (first page).

I'm also going to change the default for new installs (and fresh portable downloads) to "off" for this option.

**Comment by Achaean** [comment]
Indeed! :-)
Seems to be a Windows bug.
