### ISSUE TITLE
C++ runtime download fails.

### ISSUE THREAD

**Issue by Achaean** [syndicodefront/infekt#130]
C++ runtime binaries downloading (during installation) fails.
V.1.0.1 on Win 10 Pro x64 (v.10.0.16299.125).

**Comment by flakes** [comment]
I checked the URLs and they are fine. Re-open with screenshot/log file if the issue persists.

- https://download.visualstudio.microsoft.com/download/pr/11100230/15ccb3f02745c7b206ad10373cbca89b/VC_redist.x64.exe
- https://download.visualstudio.microsoft.com/download/pr/11100229/78c1e864d806e36f6035d80a0e80399e/VC_redist.x86.exe

**Comment by Achaean** [comment]
Correct! :-)

Probably it was an MS server error.
(Seem like server was down at the time).
