### ISSUE TITLE
subfolder for ttf

### ISSUE THREAD

**Issue by blackcrack** [syndicodefront/infekt#133]
Hi ,

happy to see you here in github !
a subfolder for ttf would be cool :)
https://int10h.org/oldschool-pc-fonts/
http://www.dos.blackysgate.de/

and make it compatible to Reactos.org :+1: 

best regards
Blacky
blackysgate.de

**Comment by flakes** [comment]
Note to self: https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-addfontresourceexw
