### ISSUE TITLE
Right and Bottom margins

### ISSUE THREAD

**Issue by huubert** [syndicodefront/infekt#135]
Hi,

When using the "auto-adjust window width/height" options (https://i.imgur.com/h2DxMbm.png), I noticed that the right and bottom margins are way bigger than they need to be, and are not even the same as the top and left margins.

Default margins: https://i.imgur.com/9biPaqf.png
Resized as much as possible without creating scrollbars: https://i.imgur.com/UFDNvp5.png

Default margins (tall .nfo): https://i.imgur.com/sBPdj3k.png
Resized as much as possible without creating scrollbars: https://i.imgur.com/gREP5U0.png

As you can see, both right and bottom margins can be way smaller (with or without a scrollbar).
I hope you can fix this so that they will be consistent as the top and left margins (5px).

**Comment by flakes** [comment]
This is a bit tricky because of the different scrollbar styles, but I'll look into it !

**Comment by flakes** [comment]
It's a bit of a chicken-and-egg problem because the code would need to predict whether a scrollbar is necessary or not... there'll be some minor improvements for the width in the next version, but I won't spend a lot more time improving it.
