### ISSUE TITLE
Empty lines

### ISSUE THREAD

**Issue by huubert** [syndicodefront/infekt#136]
Hi,

There are some inconsistencies when viewing/exporting a nfo file containing, for example, 10 empty lines at the start, and at the end of the file.

When viewing: https://i.imgur.com/AaDioKU.png
The empty lines at the end are completely ignored.

Exported png: https://i.imgur.com/jWNiSfb.png
Again, the empty lines at the end are completely ignored.

Hope you can fix this inconsistency too!

**Comment by flakes** [comment]
Hi,

this is actually a feature. Why would you care about empty lines and the end of a file? ;)

**Comment by huubert** [comment]
Why would you care about empty lines and the start of a file?
Either ignore both, or hide both.

**Comment by flakes** [comment]
Works as intended, sorry 😛
