### ISSUE TITLE
Some CP437 characters are not displayed

### ISSUE THREAD

**Issue by huubert** [syndicodefront/infekt#137]
After checking https://en.wikipedia.org/wiki/Code_page_437
I noticed that these 3 characters are not displayed with iNFekt:
○
◙
♪

**Comment by flakes** [comment]
Hi,
please right-click the character set name in the bottom bar and try to select _CP437 (strict mode)_. I'm checking with this file: https://syndicode.org/infekt/IBM_Code_Page_437.nfo

**Comment by huubert** [comment]
Yes, with CP437 (strict mode), those 3 symbols are visible.
