### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by eqagunn** [syndicodefront/infekt#140]
Tried to install the latest infekt-gtk from source
on Ubuntu-based distro but encountered numerous issues.

`CMake Error at src/gtk/CMakeLists.txt:24 (add_executable):`
`Cannot find source file:`
`src/lib-posix/infekt-posix.cpp`
Fixed by copying over the missing file from version 0.9.6.

`CPack Error at src/lib/nfo_renderer.h:158:23:`
`‘thread’ is not a member of ‘std’`
`std::shared_ptr<std::thread> m_preRenderThread;`
 Fixed by adding `#include <thread>` to mentioned file.

`CPack Error at src/lib/nfo_renderer.h:160:22:`
`field ‘m_preRenderingStripe’ has incomplete type ‘std::atomic<long unsigned int>’`
`std::atomic<size_t> m_preRenderingStripe;`
 Fixed by adding `#include <atomic>` to mentioned file.

`CPack Error at src/gtk/nfo_view_ctrl.cpp:79:33:`
`no matching function for call to ‘CNFORenderer::AssignNFO(CNFOData*&)’`
`l_pRenderer->AssignNFO(m_pNfo);`
Unable to fix this one.

I see there haven't been any updates for last year and a half.
Would it be possible to have GTK version updated so it compiles properly?
Or even better, a precompiled packages available for download!
Please, make this amazing software available for Linux users.

**Comment by yochananmarqos** [comment]
I also tried building the GTK version on Manjaro and ran into the same error. 

@flakes Are there plans to continue working on the Linux version?

**Comment by la55u** [comment]
Was anyone able to compile/ue it on Linux?

**Comment by awsms** [comment]
> Was anyone able to compile/use it on Linux?

no

**Comment by flakes** [comment]
Closing in favor of #117 and possible future cross-platform GUI
