### ISSUE TITLE
Umlauts are not displayed correctly

### ISSUE THREAD

**Issue by BlackMage2** [syndicodefront/infekt#142]
For me, where there is usually an umlaut, only 'ⁿ' should appear. also instead of 'für' only 'fⁿr'. Umlauts should be supported in nfo files, right?

**Comment by flakes** [comment]
Do you have an example NFO? iNFekt tries to fix umlauts in some cases, but CP437 (the classic NFO charset) does NOT support umlauts...

**Comment by BlackMage2** [comment]
here(in the zip, sry nfo is not allowed): new 20.nfo[ISO-8859-1 is the correct encoding, but it will probably be automatically recognized as OEM-US(like in notepad ++) or ISO-8859-1]

[new 20.zip](https://github.com/syndicodefront/infekt/files/5442011/new.20.zip)

**Comment by Schattenspieler** [comment]
Well, if this is still relevant, you could change the encoding/charset in the status bar. Just right click the field on the the far right and choose "Windows-1252". Works for me with your nfo:
![new 20](https://user-images.githubusercontent.com/23404520/147307046-e5226074-7587-48ad-a821-30ceb89f3fb2.png)

**Comment by BlackMage2** [comment]
well, I didn't know that
