### ISSUE TITLE
Add `infekt-cmd.exe` to PATH in installer

### ISSUE THREAD

**Issue by sitiom** [syndicodefront/infekt#145]
Option to add `infekt-cmd.exe` to PATH to be able to use it directly in the command line :
![image](https://user-images.githubusercontent.com/56180050/163778772-36bd7df8-6a6e-432c-9b9f-764d757c11e1.png)

**Comment by sitiom** [comment]
Im assuming this is closed in favor of infekt 2.0? https://github.com/syndicodefront/infekt/issues/151

**Comment by flakes** [comment]
It's more likely a WON'T FIX, unless someone volunteers do it for 2.0 with some WiX or similar magic ( https://tauri.app/v1/guides/building/windows#customizing-the-wix-installer-template ) - but we're not there yet..
