### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by ryehamstrawberry** [syndicodefront/infekt#146]
Would you please consider implementing a dark mode theme ala [jane](https://www.kifoth.de/jane/html/about.html)?

**Comment by flakes** [comment]
The window styling is up to the operating system, so what would a dark mode do that inverting the NFO colors in the settings could not achieve?

**Comment by ryehamstrawberry** [comment]
You're right, users can set colors to their preference.
A "dark mode" would simply apply a preset configuration such as https://i.imgur.com/1G0AvKx.png.

Not a necessary feature by any means, but despite the color settings being fully customizable by the user, it still might be a nice addition to have a quick "dark mode" and other specific text/background combinations available for user to choose.
Just a friendly suggestion.

Great work either way, iNFekt has become my default NFO viewer as it's very responsive and lightweight. Keep it up, the alternatives are not as good.

**Comment by flakes** [comment]
Won't be fixed in 1.x any more, but 2.0 should have this covered. See issue #151
