### ISSUE TITLE
Allow NFO modification

### ISSUE THREAD

**Issue by ryehamstrawberry** [syndicodefront/infekt#147]
Please consider implementing the ability to modify NFO files ala [jane](https://www.kifoth.de/jane/html/about.html).

Having the ability to add, cut, and otherwise modify text without having to utilize a separate app would make iNFekt much more useful.

Adding this functionality would help distinguish iNFekt as one of, if not the best, active NFO viewers/editors.

jane has a good feature set that includes the ability to edit NFO files but the current recent builds includes a delay/lag behavior making it virtually unusable.

Due to jane's dev seemingly ignoring this bug report, iNFekt could take this opportunity to implement some of the same features offered by jane but are currently not present (e.g. [dark mode](https://github.com/syndicodefront/infekt/issues/146, etc.)).
Offering the feature set of jane while being much more responsive and resource efficient would separate iNFekt as THE premier NFO utility.

Thank you for your time and effort, I hope you will look into these requests as I believe they would better the app.

**Comment by flakes** [comment]
Thanks for the suggestion, but this is out of planned scope.
