### ISSUE TITLE
Add scaling support for high-DPI monitors

### ISSUE THREAD

**Issue by horans** [syndicodefront/infekt#148]
It will be wonderful if iNFekt can adapt to scaling(eg., 150%, 200%) for high-DPI devices on Windows 10/11, then we don't have to resize and `crtl +` every single time.

**Comment by flakes** [comment]
Definitely wanting to do this, but have limited ability to test properly...

**Comment by JPersson77** [comment]
Still hoping for this :)

**Comment by flakes** [comment]
Won't be fixed in 1.x any more, but 2.0 should have this covered. See issue #151
