### ISSUE TITLE
Publish this on winget

### ISSUE THREAD

**Issue by ALIENQuake** [syndicodefront/infekt#150]
Hi,

Please publish this on `winget` as it's the official windows package manger solution.

**Comment by sitiom** [comment]
https://winstall.app/apps/syndicode.iNFekt

**Comment by ALIENQuake** [comment]
Perfect, thank you!

**Comment by sitiom** [comment]
It was already available before as `syndicode.iNFektNFOViewer` before the naming was moved yesterday to `syndicode.iNFekt`.
