### ISSUE TITLE
Please include a dark mode theme in the default installer

### ISSUE THREAD

**Issue by shodanx2** [syndicodefront/infekt#154]
If there is one, I could not find it.

Is there a themes repository somewhere online ?

![image](https://github.com/syndicodefront/infekt/assets/10621885/5fd2099b-53c1-418b-b900-0075dcf3edba)

**Comment by flakes** [comment]
Won't be added in 1.x any more, but 3.0 should have this covered. See issue https://github.com/syndicodefront/infekt/issues/151
